-- Tabella divinità
create table deities (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null check (category in ('caos', 'legge', 'elementali', 'signori_delle_bestie'))
);

-- Tabella nazioni
create table nations (
  id bigint generated by default as identity primary key,
  name text not null,
  short_description text not null,
  full_description text not null
);

-- Tabella equipaggiamento
create table equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  category text not null check (category in ('armi', 'armature', 'accessori')),
  stats jsonb not null
);

-- Tabella personaggi
create table characters (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  race text not null,
  class text not null,
  level integer not null default 1,
  stats jsonb not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabella campagne
create table campaigns (
  id bigint generated by default as identity primary key,
  name text not null,
  description text not null,
  master_id uuid references auth.users not null,
  players uuid[] default array[]::uuid[],
  invite_link text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabella messaggi
create table messages (
  id bigint generated by default as identity primary key,
  content text not null,
  user_id uuid references auth.users not null,
  campaign_id bigint references campaigns not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Tabella profili utenti
create table profiles (
  id uuid references auth.users primary key,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Funzione per creare automaticamente il profilo utente
create function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (new.id, new.raw_user_meta_data->>'name');
  return new;
end;
$$;

-- Trigger per creare automaticamente il profilo utente
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user(); 